apiVersion: v1
kind: PersistentVolume
metadata:
  name: conduit-pv
  namespace: conduit
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /data/log
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-host

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: conduit-pvc
  namespace: conduit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 5Gi